name: havayot
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  built_value: ^8.0.5
  built_collection: ^5.0.0
  collection: ^1.15.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  tuple: ^2.0.1
  rxdart: ^0.27.7
  able:
    path: D:\Programming\SelfTable\packages\able
  flutter_analog_clock: ^1.0.3
  circular_countdown_timer: ^0.2.3
  bot_toast: ^4.0.1
  circular_countdown: ^2.1.0
  intl: ^0.17.0
  appinio_swiper: ^2.0.1
  liquid_swipe: ^3.1.0
dev_dependencies:
  built_value_generator: ^8.0.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf